### ISSUE TITLE
Mongo Authentication failed

### ISSUE THREAD

**Issue by AbhijeetSalunkhe** [mongodb/mongo-php-driver#1110]
Mongo Authentication failed:

php 7.2
mongo 3.2.22
jenssegers 3.6

i have tried to connect mongo to my live database and i got authentication failed 

Error.log

```
(1)
Authentication failed. {"exception":"[object] (MongoDB\\Driver\\Exception\\AuthenticationException(code: 11): Authentication failed. at /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Operation/Find.php:322)
[stacktrace]
#0 /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Operation/Find.php(322): MongoDB\\Driver\\Server->executeQuery('test.use...', Object(MongoDB\\Driver\\Query), Array)
#1 /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Collection.php(663): MongoDB\\Operation\\Find->execute(Object(MongoDB\\Driver\\Server))
#2 [internal function]: MongoDB\\Collection->find(Array, Array)
#3 /var/www/html/partnerApi/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php(42): call_user_func_array(Array, Array)
#4 /var/www/html/partnerApi/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(403): Jenssegers\\Mongodb\\Collection->__call('find', Array)


(2)
Authentication failed. {"exception":"[object] (MongoDB\\Driver\\Exception\\AuthenticationException(code: 11): Authentication failed. at /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Operation/Count.php:176)
[stacktrace]
#0 /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Operation/Count.php(176): MongoDB\\Driver\\Server->executeReadCommand('test', Object(MongoDB\\Driver\\Command), Array)
#1 /var/www/html/partnerApi/vendor/mongodb/mongodb/src/Collection.php(312): MongoDB\\Operation\\Count->execute(Object(MongoDB\\Driver\\Server))
#2 [internal function]: MongoDB\\Collection->count(Array)
```

**Comment by AbhijeetSalunkhe** [comment]
I have solved my issue myself...

cheers

**solution:**
Issue was in laravel .env file
->don't use hash(#) in password, .env file are read hash as comment

**Comment by jmikola** [comment]
Note: https://stackoverflow.com/a/57172073/162228 talks about the change between Laravel 5.7 and 5.8, where hash characters in `.env` files are now interpreted as the start of a comment, and suggests quoting the string with the hash as a workaround. That would save you the trouble of needing to change your password to accommodate `.env` parsing.
