### ISSUE TITLE
Segmentation fault when run PHP cli program with mongodb extension

### ISSUE THREAD

**Issue by jamestim2021** [mongodb/mongo-php-driver#1184]
### Environment

```
php -v 

PHP 7.2.34 (cli) (built: Dec  1 2020 17:36:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

```
php --ri mongodb

MongoDB support => enabled
MongoDB extension version => 1.7.5
MongoDB extension stability => stable
libbson bundled version => 1.16.2
libmongoc bundled version => 1.16.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
libmongocrypt bundled version => 1.0.3
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
```

php compile configure arugment

```
./configure'  '--prefix=/path/to/prefix' '--with-config-file-path=/path/to/prefix/etc' '--enable-fpm' '--with-fpm-user=www' '--with-fpm-group=www' '--enable-mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-iconv-dir' '--with-freetype-dir=/usr/include/freetype2/freetype' '--with-jpeg-dir' '--with-png-dir' '--with-zlib' '--with-libxml-dir' '--enable-xml' '--disable-rpath' '--enable-bcmath' '--enable-shmop' '--enable-sysvsem' '--with-curl' '--enable-mbregex' '--enable-mbstring' '--enable-intl' '--enable-ftp' '--with-gd' '--with-openssl' '--with-mhash' '--enable-pcntl' '--enable-sockets' '--with-xmlrpc' '--enable-zip' '--enable-soap' '--with-gettext' '--disable-fileinfo' '--enable-opcache' '--with-xsl' '--enable-inline-optimization' '--disable-ipv6'
```

### Test Script

use Laravel's artisan PHP script to connect mongo.
execute some PHP script like `php artisan ConnectionMongoScript` on bash.

### Expected and Actual Behavior

error with information "Segmentation fault"

### Debug Log

I used gdb to load core dump file. this is call stack when I  run PHP script to connect mongodb.

I do not known why mongodbc call the function `strlen` fail at `libmongoc/src/mongoc/mongoc-scram.c:561`

Is it because the password of my mongodb contains special charaters?

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007f9312cdd721 in __strlen_sse2_pminub () from /usr/lib64/libc.so.6


#0  0x00007f9312cdd721 in __strlen_sse2_pminub () from /usr/lib64/libc.so.6
#1  0x00007f930837e055 in _mongoc_scram_step2 (error=0x1771918, outbuflen=0x7ffe57eb4860, outbufmax=4096,
    outbuf=0x7ffe57eb4d80 "r=idn5Mg7ITN8qXNJ36eLgyrIVpuCCtANJpghwcRYTU2l5juu8PGa6KOyW79bIZMBU,s=9yg023N0sX+zaA1HNhHK2GGibHP+KfdJAUk9zQ==,i=15000", inbuflen=117,
    inbuf=0x7ffe57eb4d80 "r=idn5Mg7ITN8qXNJ36eLgyrIVpuCCtANJpghwcRYTU2l5juu8PGa6KOyW79bIZMBU,s=9yg023N0sX+zaA1HNhHK2GGibHP+KfdJAUk9zQ==,i=15000",
    scram=0x7ffe57eb49c0) at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-scram.c:561
#2  _mongoc_scram_step (scram=scram@entry=0x7ffe57eb49c0,
    inbuf=inbuf@entry=0x7ffe57eb4d80 "r=idn5Mg7ITN8qXNJ36eLgyrIVpuCCtANJpghwcRYTU2l5juu8PGa6KOyW79bIZMBU,s=9yg023N0sX+zaA1HNhHK2GGibHP+KfdJAUk9zQ==,i=15000",
    inbuflen=117,
    outbuf=outbuf@entry=0x7ffe57eb4d80 "r=idn5Mg7ITN8qXNJ36eLgyrIVpuCCtANJpghwcRYTU2l5juu8PGa6KOyW79bIZMBU,s=9yg023N0sX+zaA1HNhHK2GGibHP+KfdJAUk9zQ==,i=15000",
    outbufmax=outbufmax@entry=4096, outbuflen=outbuflen@entry=0x7ffe57eb4860, error=error@entry=0x1771918)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-scram.c:995
#3  0x00007f930835587c in _mongoc_cluster_auth_node_scram (cluster=cluster@entry=0x176d1a8, stream=stream@entry=0x1770270, algo=MONGOC_CRYPTO_ALGORITHM_SHA_256,
    error=0x1771918, sd=<optimized out>) at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:1343
#4  0x00007f9308355f26 in _mongoc_cluster_auth_node_scram_sha_256 (error=<optimized out>, sd=<optimized out>, stream=<optimized out>, cluster=<optimized out>)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:1504
#5  _mongoc_cluster_auth_node (cluster=cluster@entry=0x176d1a8, stream=0x1770270, sd=sd@entry=0x1771620, sasl_supported_mechs=sasl_supported_mechs@entry=0x176d190,
    error=error@entry=0x1771918) at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:1564
#6  0x00007f9308356765 in mongoc_cluster_fetch_stream_single (error=0x7ffe57eb6550, reconnect_ok=<optimized out>, server_id=1, cluster=0x176d1a8)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:2031
#7  _mongoc_cluster_stream_for_server (cluster=cluster@entry=0x176d1a8, server_id=server_id@entry=1, reconnect_ok=reconnect_ok@entry=true, cs=cs@entry=0x0,
    reply=reply@entry=0x7ffe57eb64d0, error=error@entry=0x7ffe57eb6550)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:1855
#8  0x00007f9308356d80 in mongoc_cluster_stream_for_server (cluster=cluster@entry=0x176d1a8, server_id=1, reconnect_ok=reconnect_ok@entry=true, cs=0x0,
    reply=reply@entry=0x7ffe57eb64d0, error=error@entry=0x7ffe57eb6550)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-cluster.c:1928
#9  0x00007f930834737b in mongoc_bulk_operation_execute (bulk=bulk@entry=0x1770510, reply=reply@entry=0x7ffe57eb64d0, error=error@entry=0x7ffe57eb6550)
    at /path/to/mongodb-1.7.5/src/libmongoc/src/libmongoc/src/mongoc/mongoc-bulk-operation.c:763
#10 0x00007f93083aa3b8 in phongo_execute_bulk_write (client=0x176d1a0, namespace=0x7f93074db4e8 "live_game.stat_day_winning_rate",
    bulk_write=bulk_write@entry=0x7f93074d3540, options=<optimized out>, server_id=1, return_value=return_value@entry=0x7f930ee1ebf0,
    return_value_used=return_value_used@entry=1) at /path/to/mongodb-1.7.5/php_phongo.c:770
---Type <return> to continue, or q <return> to quit---
#11 0x00007f93083c63b1 in zim_Server_executeBulkWrite (execute_data=<optimized out>, return_value=0x7f930ee1ebf0)
    at /path/to/mongodb-1.7.5/src/MongoDB/Server.c:197
#12 0x000000000092dc55 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /path/to/php-7.2.34/Zend/zend_vm_execute.h:1036
#13 execute_ex (ex=0x0) at /path/to/php-7.2.34/Zend/zend_vm_execute.h:59796
#14 0x0000000000879a6b in zend_call_function (fci=0x7f930ee1e9b0, fci@entry=0x7ffe57eb69b0, fci_cache=<optimized out>, fci_cache@entry=0x7ffe57eb6980)
    at /path/to/php-7.2.34/Zend/zend_execute_API.c:820
#15 0x000000000077cee3 in zif_call_user_func_array (execute_data=0x7f930ee1e740, return_value=0x7f930ee1e5c0)
    at /path/to/php-7.2.34/ext/standard/basic_functions.c:4905
#16 0x000000000092d94e in ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER () at /path/to/php-7.2.34/Zend/zend_vm_execute.h:820
#17 execute_ex (ex=0x0) at /path/to/php-7.2.34/Zend/zend_vm_execute.h:59790
#18 0x000000000092edb3 in zend_execute (op_array=0x7f930ee7c2a0, op_array@entry=0x7f93076df980, return_value=return_value@entry=0x7f930ee1e4a0)
    at /path/to/php-7.2.34/Zend/zend_vm_execute.h:63804
#19 0x00000000008893a4 in zend_execute_scripts (type=type@entry=8, retval=0x7f930ee1e4a0, retval@entry=0x0, file_count=file_count@entry=3)
    at /path/to/php-7.2.34/Zend/zend.c:1498
#20 0x0000000000828fe0 in php_execute_script (primary_file=primary_file@entry=0x7ffe57eb8e80) at /path/to/php-7.2.34/main/main.c:2599
#21 0x00000000009310d5 in do_cli (argc=4, argv=0x14dcbe0) at /path/to/php-7.2.34/sapi/cli/php_cli.c:1011
#22 0x000000000044e3ff in main (argc=4, argv=0x14dcbe0) at /path/to/php-7.2.34/sapi/cli/php_cli.c:1403
```

**Comment by alcaeus** [comment]
@jamestim2021 were you able to fix the segmentation fault? For what it's worth, we no longer support 1.7, so I would recommend updating to a supported versions. If you can reproduce the segmentation fault there, please report back so I can take another look. Thanks!
