### ISSUE TITLE
Using pcntl_fork seems to lead to random connection issues

### ISSUE THREAD

**Issue by EranUzan** [mongodb/mongo-php-driver#828]
### Description

I seems that using pcntl_fork causes  the driver to fail with timeout / connection issues.

### Environment
OS : ubuntu 17.10 / CentOS 7 
PHP version : 7.1
```
$ php -i | grep -E 'mongodb|libmongoc|libbson'
/etc/php/7.1/cli/conf.d/20-mongodb.ini,
mongodb
libbson bundled version => 1.9.4
libmongoc bundled version => 1.9.4
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled
mongodb.debug => no value => no value

```

PHP info  :[https://pastebin.com/i6LReDZB](https://pastebin.com/i6LReDZB)

```
$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
uuid
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
yaf
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

### Expected and Actual Behavior
- **Expected Behavior**
Same  operation and behavior as using  a process that does not  fork.

- **Actual Behavior**
The child process  carshes on random connection errors for example : 

```
Error code : 14
Error message: Invalid reply to find command.
#0 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(170): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\RuntimeException))
#1 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(467): MongoCursor->doQuery()
#2 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Alcaeus/MongoDbAdapter/AbstractCursor.php(297): MongoCursor->ensureCursor()
#3 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(245): Alcaeus\MongoDbAdapter\AbstractCursor->ensureIterator()
#4 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Mongodloid/Cursor.php(80): MongoCursor->hasNext()
```
```

Error code : 59
Error message: Unknown command error
#0 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoDB/Operation/DatabaseCommand.php(87): MongoDB\Driver\Server->executeCommand('billing_cloud', Object(MongoDB\Driver\Command), Object(MongoDB\Driver\ReadPreference))
#1 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoDB/Database.php(178): MongoDB\Operation\DatabaseCommand->execute(Object(MongoDB\Driver\Server))
#2 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCommandCursor.php(74): MongoDB\Database->command(Object(MongoDB\Model\BSONDocument), Array)
#3 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Alcaeus/MongoDbAdapter/AbstractCursor.php(297): MongoCommandCursor->ensureCursor()
#4 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Alcaeus/MongoDbAdapter/AbstractCursor.php(190): Alcaeus\MongoDbAdapter\AbstractCursor->ensureIterator()
#5 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Mongodloid/Cursor.php(96): Alcaeus\MongoDbAdapter\AbstractCursor->rewind()
```

```

Error code : 14
Error message: Failed to send "find" command with database "<db name>": Invalid reply from server.
#0 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(170): Alcaeus\MongoDbAdapter\ExceptionConverter::toLegacy(Object(MongoDB\Driver\Exception\RuntimeException))
#1 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(467): MongoCursor->doQuery()
#2 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Alcaeus/MongoDbAdapter/AbstractCursor.php(297): MongoCursor->ensureCursor()
#3 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/MongoCursor.php(245): Alcaeus\MongoDbAdapter\AbstractCursor->ensureIterator()
#4 /mnt/old/home/eran/projects/Cloud/fork/BRCloudBE/library/Mongodloid/Cursor.php(80): MongoCursor->hasNext()
```

**Comment by jmikola** [comment]
There is a note on [`MongoDB\Driver\Manager::__construct()`](http://php.net/manual/en/mongodb-driver-manager.construct.php) that advises against sharing a Manager instance (and the libmongoc client object it wraps) across forked processes or threads.

If you are creating a single client object in a parent process and accessing it from a child, you'll need to rearchitect the application. On the off chance these exceptions are the result of all interactions with the driver being performed from a single process, I'd very much be interested to see an example script that can reproduce some of these errors.

**Comment by derickr** [comment]
Gone away, so closing this out. Please feel free to reopen in case you have further information.
